name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for highlighting an issue, we will see to it as soon as possible.'
        pr-message: 'Thank you for submitting a pull request, we will see to it as soon as possible.'
